### ISSUE TITLE
Wrap up +Work

### ISSUE THREAD

**Issue by ambhinav** [AY1920S1-CS2103T-T12-1/main#37]
Need to fully wrap up the project 

**UI**

- [x] Code Quality

- [x] UG

- [x] DG

**Dashboard:** tasks, deadline and meetings

- [x] Full test Case

- [x] Code Quality

- [x] UG

- [x] DG

**Calendar** 

- [ ] Full test Case

- [ ] Code Quality

- [x] UG

- [x] DG

**Inventory**

- [x] Full test Case

- [x] Code Quality

- [x] UG

- [x] DG

**Enhancememts**
