### ISSUE TITLE
Settings to allow user to customsie +Work

### ISSUE THREAD

**Issue by ambhinav** [AY1920S1-CS2103T-T12-1/main#64]
In order of priority

- [x] Create a settings page, complete with labels of each setting that the user can customise (if possible will include toggle switches that are responsive to user's settings command)

- [x] Light/Dark theme switch

- [x] 12/24 hour display format

- [ ] Reminder scheduling for upcoming tasks (moved to 1.4)
